from django.urls import path, include
from . import views

urlpatterns = [
    path('UI/buttons', views.buttons, name="buttons"),
    path('UI/colors', views.colors, name="colors"),
    path('UI/cards', views.cards, name="cards"),
    path('UI/tabs-accordions', views.tabs_accordions, name="tabs-accordions"),
    path('UI/modals', views.modals, name="modals"),
    path('UI/images', views.images, name="images"),
    path('UI/alerts', views.alerts, name="alerts"),
    path('UI/progressbars', views.progressbars, name="progressbars"),
    path('UI/dropdowns', views.dropdowns, name="dropdowns"),
    path('UI/lightbox', views.lightbox, name="lightbox"),
    path('UI/navs', views.navs, name="navs"),
    path('UI/pagination', views.pagination, name="pagination"),
    path('UI/popover-tooltips', views.popover_tooltips, name="popover-tooltips"),
    path('UI/badge', views.badge, name="badge"),
    path('UI/carousel', views.carousel, name="carousel"),
    path('UI/video', views.video, name="video"),
    path('UI/typography', views.typography, name="typography"),
    path('UI/sweet-alert', views.sweet_alert, name="sweet-alert"),
    path('UI/grid', views.grid, name="grid"),
    path('UI/animation', views.animation, name="animation"),
    path('UI/highlight', views.highlight, name="highlight"),
    path('UI/rating', views.rating, name="rating"),
    path('UI/nestable', views.nestable, name="nestable"),
    path('UI/alertify', views.alertify, name="alertify"),
    path('UI/rangeslider', views.rangeslider, name="rangeslider"),
    path('UI/sessiontimeout', views.sessiontimeout, name="sessiontimeout"),
    # formelements
    path('Forms/form_elements', views.form_elemet, name="form_elements"),
    path('Forms/form_validation', views.form_validation, name="form_validation"),
    path('Forms/form_advanced', views.form_advanced, name="form_advanced"),
    path('Forms/form_wizard', views.form_wizard, name="form_wizard"),
    path('Forms/form_editors', views.form_editors, name="form_editors"),
    path('Forms/form_uploads', views.form_uploads, name="form_uploads"),
    path('Forms/form_mask', views.form_mask, name="form_mask"),
    path('Forms/form_xeditable', views.form_xeditable, name="form_xeditable"),
    # Charts
    path('Charts/charts-morris', views.charts_morris, name="charts-morris"),
    path('Charts/charts-chartist', views.charts_chartist, name="charts-chartist"),
    path('Charts/charts-chartjs', views.charts_chartjs, name="charts-chartjs"),
    path('Charts/charts-flot', views.charts_flot, name="charts-flot"),
    path('Charts/charts-c3', views.charts_c3, name="charts-c3"),
    path('Charts/charts-sparkline', views.charts_sparkline, name="charts-sparkline"),
    path('Charts/charts-jquery-knob', views.charts_other, name="charts-other"),
    path('Charts/charts-peity', views.charts_peity, name="charts-peity"),
    # Table
    path('Tables/tables-basic', views.tables_basic, name="tables-basic"),
    path('Tables/tables-datatable', views.tables_datatable, name="tables-datatable"),
    path('Tables/tables-editable', views.tables_editable, name="tables-editable"),
    path('Tables/tables-responsive', views.tables_responsive, name="tables-responsive"),
    # Icons
    path('Icons/icons-material', views.icons_material, name="icons-material"),
    path('Icons/icons-ion', views.icons_ion, name="icons-ion"),
    path('Icons/icons-fontawesome', views.icons_fontawesome, name="icons-fontawesome"),
    path('Icons/icons-themify', views.icons_themify, name="icons-themify"),
    path('Icons/icons-dripicons', views.icons_dripicons, name="icons-dripicons"),
    path('Icons/icons-typicons', views.icons_typicons, name="icons-typicons"),
    path('Icons/icons-weather', views.icons_weather, name="icons-weather"),
    path('Icons/icons-mobirise', views.icons_mobirise, name="icons-mobirise"),
    # map
    path('Maps/maps-google', views.maps_google, name="maps-google"),
    path('Maps/maps-vector', views.maps_vector, name="maps-vector"),
]